//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursework_WPF.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coursework_WPF.Localizations.LanguageResourse", typeof(LanguageResourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        public static string backvideo {
            get {
                return ResourceManager.GetString("backvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSER.
        /// </summary>
        public static string browser {
            get {
                return ResourceManager.GetString("browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAT.
        /// </summary>
        public static string btnchat {
            get {
                return ResourceManager.GetString("btnchat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string btnCreateAcc {
            get {
                return ResourceManager.GetString("btnCreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        public static string btnDetail {
            get {
                return ResourceManager.GetString("btnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN.
        /// </summary>
        public static string btnmenu {
            get {
                return ResourceManager.GetString("btnmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiN/MaX.
        /// </summary>
        public static string btnmimax {
            get {
                return ResourceManager.GetString("btnmimax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimize.
        /// </summary>
        public static string btnminimize {
            get {
                return ResourceManager.GetString("btnminimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUSIXPLAYER.
        /// </summary>
        public static string btnmusicplayer {
            get {
                return ResourceManager.GetString("btnmusicplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONALISATION.
        /// </summary>
        public static string btnpersonalisation {
            get {
                return ResourceManager.GetString("btnpersonalisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to power.
        /// </summary>
        public static string btnpower {
            get {
                return ResourceManager.GetString("btnpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH.
        /// </summary>
        public static string btnrefresh {
            get {
                return ResourceManager.GetString("btnrefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        public static string btnsearch {
            get {
                return ResourceManager.GetString("btnsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string btnsettings {
            get {
                return ResourceManager.GetString("btnsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYER.
        /// </summary>
        public static string btnvideoplayer {
            get {
                return ResourceManager.GetString("btnvideoplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATCH.
        /// </summary>
        public static string btnwatch {
            get {
                return ResourceManager.GetString("btnwatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD VIDEO.
        /// </summary>
        public static string choosevideo {
            get {
                return ResourceManager.GetString("choosevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORWARD.
        /// </summary>
        public static string forwardvideo {
            get {
                return ResourceManager.GetString("forwardvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISTORY.
        /// </summary>
        public static string historytext {
            get {
                return ResourceManager.GetString("historytext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string infoheader {
            get {
                return ResourceManager.GetString("infoheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program for comfortable watch video. You can save favorite moment and notes it. Also you can do it with playlists. Have a nice time!.
        /// </summary>
        public static string infotext {
            get {
                return ResourceManager.GetString("infotext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageExpander {
            get {
                return ResourceManager.GetString("LanguageExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOAD.
        /// </summary>
        public static string loadvideo {
            get {
                return ResourceManager.GetString("loadvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string localisationtext {
            get {
                return ResourceManager.GetString("localisationtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPEN VIDEOPLAYER.
        /// </summary>
        public static string openvideoplayer {
            get {
                return ResourceManager.GetString("openvideoplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSE.
        /// </summary>
        public static string pausevideo {
            get {
                return ResourceManager.GetString("pausevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string playvideo {
            get {
                return ResourceManager.GetString("playvideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESUME.
        /// </summary>
        public static string resumevideo {
            get {
                return ResourceManager.GetString("resumevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL VIDEO.
        /// </summary>
        public static string seeallstared {
            get {
                return ResourceManager.GetString("seeallstared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARRED.
        /// </summary>
        public static string seestared {
            get {
                return ResourceManager.GetString("seestared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL.
        /// </summary>
        public static string specialintr {
            get {
                return ResourceManager.GetString("specialintr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string SpeedExpander {
            get {
                return ResourceManager.GetString("SpeedExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string themetext {
            get {
                return ResourceManager.GetString("themetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLUME.
        /// </summary>
        public static string volumetext {
            get {
                return ResourceManager.GetString("volumetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string welcometexxt {
            get {
                return ResourceManager.GetString("welcometexxt", resourceCulture);
            }
        }
    }
}
